// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.elsevier.tsconfig.domain;

import com.elsevier.tsconfig.domain.OrderusedinosPK;
import java.io.Serializable;

privileged aspect OrderusedinosPK_Roo_Serializable {
    
    declare parents: OrderusedinosPK implements Serializable;
    
    private static final long OrderusedinosPK.serialVersionUID = 1L;
    
}
