// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.elsevier.tsconfig.domain;

import com.elsevier.tsconfig.domain.OrderusedinosPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OrderusedinosPK_Roo_Configurable {
    
    declare @type: OrderusedinosPK: @Configurable;
    
}
